### ISSUE TITLE
[BACKEND] Dockerize

### ISSUE THREAD

**Issue by sokungz01** [cpe-kmutt-student/comcamp34#24]

**Comment by sokungz01** [comment]
Dockerize:
 - Comcamp34-Backend (Nodejs)
 - phpMyadmin
 - MySQL
 
 But have the issues about connection from Nodejs to MySQL

**Comment by ChaiyapatOam** [comment]
It's probably work

![Anya](https://media.tenor.com/WUUwSs_M6hMAAAAd/anime-sonrisa.gif?fbclid=IwAR0b30rRbLTKdOTJqW5P77BVUEZGZYGPQyHzagWzwxIbaWznlggUcMlIVwM)

**Comment by sokungz01** [comment]
Thanks for your work.
![](https://media.giphy.com/media/U6kGxfqszGeUBFnOT8/giphy.gif)
