### ISSUE TITLE
[ FORM ] PAGE#5 Upload Files

### ISSUE THREAD

**Issue by Thanaphol47825** [cpe-kmutt-student/comcamp34#27]
- Create a form that combines all components for individual information in registration page
- The member number from team information form will be used to indicate how many member information forms will be generated.
  - `ภาพถ่ายอิสระของผู้สมัครที่เห็นใบหน้าชัดเจน`(Upload File)
  - `หนังสือขออนุญาตผู้ปกครอง`(Upload File)
  - `สำเนาบัตรประจำตัวประชาชนหรือสำเนาบัตรนักเรียนของผู้สมัคร`(Upload File)
  - `เอกสารรับรองความเป็นนักเรียนหรือเอกสารรับรองผลการศึกษา (ปพ.7)`(Upload File)
  - `ระเบียนแสดงผลการศึกษาของระดับชั้นมัธยมศึกษาตอนปลาย (ปพ.1) หรือหนังสือแสดงผลการเรียนเฉลี่ย`(Upload File)

**Comment by sokungz01** [comment]
From #36

**Comment by sokungz01** [comment]
TODO : Add styling with Tailwind CSS (or Vanilla CSS if tailwind cannot be provided) that meets a requirement from the `Graphic team`.
References [Regisration Page FIGMA ](https://www.figma.com/file/46iwOWVNhNGtfDROloJhgq/UI-ComCamp34?t=WhMCFJZMXYH7AKEl-0)

**Comment by sokungz01** [comment]
From #77
