### ISSUE TITLE
[ FORM ] Image / File input box

### ISSUE THREAD

**Issue by sokungz01** [cpe-kmutt-student/comcamp34#3]
- Create an input box component that's suitable for our data requirement from the Registration team.
which contains the following data below :
   - `สำเนาบัตรประจำตัวประชาชน หรือ สำเนาบัตรนักเรียน`
   - `เอกสารรับรองการเป็นนักเรียนของสถานศึกษา / ปพ.7`
   - `ระเบียนแสดงผลการศึกษาของระดับมัธยมศึกษาตอนปลาย (ปพ.1)`
   - `เอกสารขออนุญาตผู้ปกครอง`
   - `สำเนาบัตรประจำตัวประชาชนของผู้ปกครอง`
   - `ภาพถ่ายอิสระของผู้สมัครที่เห็นใบหน้าชัดเจน และมีขนาดไม่ต่ำกว่า 4 x 6 นิ้ว `
- Must validate incoming data before storing in the state
- Add styling with Tailwind CSS (or Vanilla CSS if tailwind cannot be provided) that meets a requirement from the `Graphic` team.

**Comment by sokungz01** [comment]
From #20.

**Comment by wit03** [comment]
Created in #20
