### ISSUE TITLE
[ Form ] Confirmation Popup

### ISSUE THREAD

**Issue by wit03** [cpe-kmutt-student/comcamp34#34]
Popup ที่จะโชว์หลังกด Submit Form ซึ่งจะประกอบด้วยคำเตือนให้ตรวจสอบ Form ให้ดี เพราะไม่สามารถเเก้ไขได้

**Comment by sokungz01** [comment]
ถ้าใช้เป็นตัวของ sweetalert2 ดีมั้ยคับ

**Comment by sokungz01** [comment]
TODO : For the Confirmation popup will use **SweetAlert2** and **TailwindCSS** to provide this components that meets a requirement from the `Graphic team`.
References [Regisration Page FIGMA ](https://www.figma.com/file/46iwOWVNhNGtfDROloJhgq/UI-ComCamp34?t=WhMCFJZMXYH7AKEl-0)

**Comment by sokungz01** [comment]
### DESKTOP (1920x1080)
![Screen Shot 2566-02-06 at 02 06 03](https://user-images.githubusercontent.com/55968068/216840332-42c1e889-90b3-4d2c-a585-4ba3ccd2a28a.png)
![Screen Shot 2566-02-06 at 02 06 08](https://user-images.githubusercontent.com/55968068/216840336-9b1168d9-c55a-4fe9-9117-a35f5be2d557.png)

### MOBILE IPHONE SE 
![Screen Shot 2566-02-06 at 02 07 03](https://user-images.githubusercontent.com/55968068/216840339-2302b3aa-982d-444b-aacd-74d565b10f1a.png)
![Screen Shot 2566-02-06 at 02 07 07](https://user-images.githubusercontent.com/55968068/216840343-d15fbcbd-4ce9-42ef-84e6-efc248492d53.png)
